### ISSUE TITLE
Add license CC BY-NC-SA 3.0

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_nav#103]
There are some records need to publish, but they are under the license CC BY-NC-SA 3.0, https://creativecommons.org/licenses/by-nc-sa/3.0/. On CKAN, there is no this license, the team is suggested to add.

**Comment by Huyeng** [comment]
After checking, it found that license are available in the license list, but not available in the select box of license in CKAN. 
https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/blob/master/ckanext/odm_nav/public/licenses.json

![screenshot_244](https://user-images.githubusercontent.com/6613530/46277612-ce7a9200-c58d-11e8-87e1-59790ef170b3.png)

**Comment by ghost** [comment]
added on PP and Prod 

<img width="731" alt="screen shot 2018-10-02 at 18 14 48" src="https://user-images.githubusercontent.com/37798909/46364927-18877480-c66f-11e8-9df7-119b1a022915.png">
