### ISSUE TITLE
Harmonize footer design

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#11]
@chris-aeviator @kathi-aeviator probably part of https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/1 but worth to raise. the design of the footer should be harmonized in colours and layout so it does not conflict with the left sidebar.

![screenshot from 2016-01-05 10-45-20](https://cloud.githubusercontent.com/assets/384894/12111943/861b1de4-b399-11e5-86a1-5cc74b5e87f7.png)
![screenshot from 2016-01-05 10-45-36](https://cloud.githubusercontent.com/assets/384894/12111944/861c15dc-b399-11e5-9d10-a08c7194a054.png)

**Comment by kathi-aeviator** [comment]
restructuring header is part os milestone 7.2
duplicated on #18, closing
