### ISSUE TITLE
Records by type should not rely on CKAN groups

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#13]
The "records by type" menu element should not take the user to groups. We decided to deprecate the use of groups in favour of dataset_types. Also, links to laws and library records are already provided in bar. 

There would be only Maps missing, which could be filtered out by presenting datasets with GEOJSON, KML or SHP resources....

![screenshot from 2016-01-05 11-10-13](https://cloud.githubusercontent.com/assets/384894/12112454/e9d43dea-b39c-11e5-86e7-8771cdfd160a.png)

**Comment by kathi-aeviator** [comment]
@chris-aeviator please comment on this issue if you can

**Comment by acorbi** [comment]
@chris-aeviator records by type has been removed from the menu item _DATA_. Closing this

**Comment by kathi-aeviator** [comment]
@acorbi: we agree with that! Opend another issue for wordpress here:
https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/400
