### ISSUE TITLE
Implement necessary social icons to Ckan

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/ckanext-odm_nav#16]
Implement necessary social icons. I'm not sure what the last choice was but I think "contact"-icon should be there at least! 

@jpeizer1 @DBishton what do you think about the twitter and facebook ones?

<img width="413" alt="bildschirmfoto 2016-01-05 um 16 29 23" src="https://cloud.githubusercontent.com/assets/15011163/12119039/831c4cdc-b3c9-11e5-8c66-eee7f5651408.png">

**Comment by jpeizer1** [comment]
Would agree on contact - Facebook and twitter icons are consistent with the icons used in the new areas so I think they are appropriate.
https://pp-data.opendevelopmentmekong.net/dataset/jp-s-test-set?type=dataset
