### ISSUE TITLE
Still seeing 404's when I hit Icons and menu items in different countries

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/ckanext-odm_nav#19]
@DBishton  My feeling is that every menu item / Icon on every country menu that doesn't have a real page developed  for it yet and creates a 404 error should default to the top landing page for that country. Why? Because on the top page it clearly states:

Thailand at a glance

While we’re getting the  Open Development Thailand site ready for you, take a look at these interesting facts about the country.

It seems ready made to deal with a 404. Otherwise do we have an alternative plan to develop alternates for these 404 pages? Every time I hit a link and see a 404 I cringe and have a June flashback....

RGDS

JP

**Comment by acorbi** [comment]
@chris-aeviator @kathi-aeviator @DBishton @jpeizer1 what is the status of this? which links concretely are presenting that issue?

**Comment by kathi-aeviator** [comment]
@acorbi @DBishton @chris-aeviator cannot reproduce 404. Please check and @dev-team please solve problem and fix!

**Comment by chris-aeviator** [comment]
waiting for dev feedback on implementation ( https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/pull/47)

successfully tested on PreProduction
