### ISSUE TITLE
The menu items show up on Ckan are not heritaged

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_nav#48]
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/14346096/d23e8258-fcda-11e5-9394-a04ddb25bf99.png)

The issue also logged in : https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/793

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/pull/52
