### ISSUE TITLE
Allow editors to search private records on CKAN

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/ckanext-odm_nav#86]
@acorbi I understand that to reduce duplications of CKAN records, two measures have been implemented:

1) As per data entry protocol, before entering any CKAN record, **editor must search the title of the document within CKAN to identify duplicate**. Currently, editors of an organization can see their own private records. However, an editor cannot see a private records of another editor in the same organization. Search currently return results from private records from the organization that the editor belongs. Search also doesn't return private records from other organizations. 

2) If an editor enters in a title that is the same as **a public record** then the system rejects it and therefore the editor is informed of a duplication. However, if an editor enters in a title that is the same as a **private record**, the system doesn't reject it and therefore the editor doesn't become aware of a duplication.

@prustar and I are proposing the following:
1)  **Allow editors to see private records** as well as **public records** across CKAN in a search. 
2) Program the system to reject a title that is the same as any **public or private record**.

**Comment by acorbi** [comment]
@gimmemochi go it, thanks for the detailed description. Will put it on my list

**Comment by acorbi** [comment]
@gimmemochi I took some time to research this and have following information to help decide how to move forward:

> However, an editor cannot see a private records of another editor in the same organization

This is not correct

In order to see private as well as public records on a CKAN search, the search needs to be triggered on the **organization page** the user is willing to upload the dataset to. Example: https://data.pp.opendevelopmentmekong.net/organization/cambodia-organization

If integrated in the data entry process, and trained accordingly, using the organization page would be a solution for the scenarios you are picturing.

Would this be a solution? at least for the interim?

In order to extend this functionality so the **main search** also shows private records I would need to tweak CKAN's search mechanisms. No cost estimation yet.

**Comment by prustar** [comment]
@acorbi this does not resolve the issue of duplicates from other country records that are private. Need to think about practical long term solution.

**Comment by acorbi** [comment]
@prustar actually, it seems that we still need to define a process which determines how to approach data contributions across organizations. There are currently some active conversation around this on https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/131 and https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/128 . It would be great if you could provide your input once you are available.

**Comment by acorbi** [comment]
@prustar 

quoting @gimmemochi on her comment above:

> Allow editors to see private records as well as public records across CKAN in a search.

Just to clarify following up what we just said on the SCM: 

- Should editors **and admins** be able to do so? Or just **admins** ( seems to be a little difference but It might actually make a big one, in terms of development)

**Comment by prustar** [comment]
@acorbi -- Editors should be able to so they know it's already there. This makes a huge difference as we move to increasing data sharing partners, they will all be editors. They need to be able to see that what they are uploading is there or not. Currently the system rejects the entry of a title that is the same but doesn't not tell the user that it's a duplicate and does not account for errors in spelling or title. 

To improve data integrity they should be able to search everything on the database and verify if it's the same or not prior to uploading resources onto the platform. It also allows for cross-checking and external moderating of the resources and metadata.  If they see the dataset exist and note any errors or inconsistencies they can contact the maintainer and have it corrected prior to publishing.

**Comment by acorbi** [comment]
@gimmemochi @prustar see https://github.com/OpenDevelopmentMekong/wp-odm_solr/issues/194. I have implemented a solution for this issue which is described there.
