### ISSUE TITLE
Language switcher should be in top bar

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#9]
Currently in the footer, the language switcher should be consistent in all platform components and much more visible as it is currently.

![screenshot from 2016-01-03 15-40-50](https://cloud.githubusercontent.com/assets/384894/12079194/897149a6-b230-11e5-909e-041804bff068.png)

**Comment by kathi-aeviator** [comment]
This was an early Layout we presented in hackpad
https://hackpad.com/MILESTONE-7-NAVIGATION-CONCEPT-haKFM9AUtx8

In actual design it would be better to drop the language chooser on the right side, because of the left-side country-bar.

@acorbi is it possible that you implement that and I review it after bei making the css finetuning?

**Comment by kathi-aeviator** [comment]
Here is the gif we presented...
![hackpad com_s96ubkkezaf_p 475433_1446589879711_vorschau_nc_v3](https://cloud.githubusercontent.com/assets/15011163/12266097/8e74cac8-b941-11e5-8dd1-895458e35e24.gif)

**Comment by kathi-aeviator** [comment]
on smaller screen searchbar is missing. labeling as a bug

**Comment by kathi-aeviator** [comment]
@acorbi please implement following css proposals if possible:
1. add new class for "language choose bar"

font-size: 10 px; 
1. move the section to above the searchbar

**Comment by acorbi** [comment]
@kathi-aeviator so small?  keep font-family? on hover style?

![screenshot from 2016-01-12 16-27-03](https://cloud.githubusercontent.com/assets/384894/12267629/5dba9194-b949-11e5-9041-b607846b6350.png)

**Comment by kathi-aeviator** [comment]
yes. lets make it like this for the testing. should definitely be lower priorized then the nav-font size

but I will prepare some missing css!

**Comment by kathi-aeviator** [comment]
Sorry just realized that you have to deploy first - so please take it on not centered to the sidebar but right floated.

**Comment by acorbi** [comment]
This is fixed, just needs styling
