### ISSUE TITLE
Language switcher not replacing, but prepending language code on URL

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_nav#93]
Steps to reproduce the issue:

Go to https://data.opendevelopmentmekong.net/dataset
Use the language switcher to change the language to khmer. You are now taken to https://data.opendevelopmentmekong.net/km/dataset( khmer texts presented)
Then use the language switcher again to change the language to thai. You are now presented with a Page not found error page and the url is https://data.opendevelopmentmekong.net/th/km/dataset

**Comment by prustar** [comment]
@acorbi -- When I was with TEI last week we tried to translate a record but it didn't work: 

![image](https://user-images.githubusercontent.com/14996905/34091577-02c61d14-e3ed-11e7-8f92-7e89eb8e3078.png)
It still says english at the top and when we go to save it gives an error: 
![image](https://user-images.githubusercontent.com/14996905/34091597-22c3d782-e3ed-11e7-897d-fa69ea5807a9.png)

Also please note that Burmese is no longer available as an option.
