### ISSUE TITLE
When click update dataset "/en" is appended on the url of English page

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/ckanext-odm_nav#96]
For example, for this dataset, [Management Zones of Natural Protected Areas 2017](https://data.opendevelopmentmekong.net/en/dataset/edit/zone-management-of-natural-protected-area-2017) , after updating the content, when we click "Update Dataset" button, it brought to 404 page. 
Checking the url of error, it is noticed that "/en" was appended as the link below:
"https://data.opendevelopmentmekong.net/en/en/dataset/zone-management-of-natural-protected-area-2017"

**Comment by acorbi** [comment]
@Huyeng @mailannguyen this issue  relies on a bug found in ckan 2.7 (#3499) which is fixed on version 2.7.2 -> http://docs.ckan.org/en/latest/changelog.html#v2-7-1-2017-09-27

I am coordinating with Proteus to deploy this in PROD asap. will keep you posted.

**Comment by acorbi** [comment]
Issue should be fixed now.
